version: "3"
services:
  api:
    image: kylian9/applicationtest
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://root:root@db:27017/test?authSource=admin
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
  front:
    image: kylian9/fronttestmobile
    ports:
      - "80:80"
volumes:
  mongodb_data: